### ISSUE TITLE
Process expressions.

### ISSUE THREAD

**Issue by bvsn** [webpack-contrib/i18n-webpack-plugin#12]
Is there an option for processing expressions in text?

Example:

```
__("Message to " + email + " sent successfully")
```

**Comment by ronkorving** [comment]
When dealing with translation you should always do variable replacement after the translation. My suggestion:

__('Message to %email sent successfully').replace('%email', 'foo@example.com');

**Comment by bvsn** [comment]
Yeah, I thought about this option but decided to ask. Thanks for the answer.

**Comment by ronkorving** [comment]
I'm not the author of this library, but yeah... In general I think this is best practice.

**Comment by sokra** [comment]
yeah.

**Comment by debbiepeng** [comment]
I am trying to define my json files this way:
{
  "Greetings": "Hallo Welt"
}, 
so that I can have strings in the json as key value pairs.
And I call it like this:
const defaultText = "Hello World";
__(defaultText, "Greetings");

But this can't be processed. I think it's due to defaultText not being a string literal. 
Is this an intended limitation?

Thanks.

**Comment by michael-ciniawsky** [comment]
Closing in favour of #6
